---
title: "data_wrangling"
author: "Francis"
date: "11/10/2018"
output: github_document
---

After consideration, the `admissions.csv` database seems really interesting. It is useful to analyze the  connection between mutiple factors and death.
```{r}
library(tidyverse)
library(devtools)
```

# MIMIC3

### Import data
```{r}
admissions <- 
  read.csv("./database/MIMIC3/admissions.csv") %>% 
  janitor::clean_names()
names(admissions)
  
# The year should be delt with to become normal. The discharge time means the time when the patient leave the hospital.


# see types
class(admissions$admittime)
class(admissions$dischtime)
class(admissions$deathtime)
class(admissions$admission_type) 
class(admissions$insurance)
class(admissions$religion)
class(admissions$ethnicity)
class(admissions$edregtime)
class(admissions$edouttime)

```
All of them are factors.



### Tidy data
```{r}
#Create year, month, day variables
admissions <- 
  admissions %>% 
  separate(admittime, into = c("admittime_year", "admittime_month", "admittime_day"), sep = "-")
admissions <- 
  admissions %>% 
  separate(dischtime, into = c("dischtime_year", "dischtime_month", "dischtime_day"), sep = "-") %>% 
  separate(dischtime_day, into = c("dischtime_day", "dischtime_time"), sep = " ")
admissions <- 
  admissions %>% 
  separate(deathtime, into = c("deathtime_year", "deathtime_month", "deathtime_day"), sep = "-") %>% 
  separate(deathtime_day, into = c("deathtime_day", "deathtime_time"), sep = " ")
admissions <- 
  admissions %>% 
  separate(edregtime, into = c("edregtime_year", "edregtime_month", "edregtime_day"), sep = "-") %>% 
  separate(edregtime_day, into = c("edregtime_day", "edregtime_time"), sep = " ")
admissions <- 
  admissions %>% 
  separate(edouttime, into = c("edouttime_year", "edouttime_month", "edouttime_day"), sep = "-") %>% 
  separate(edouttime_day, into = c("edouttime_day", "edouttime_time"), sep = " ")

# Correct year to normal
admissions <- 
  admissions %>% 
  mutate(admittime_year = as.numeric(admittime_year) - 200, dischtime_year = as.numeric(dischtime_year) - 200, deathtime_year = as.numeric(deathtime_year) - 200, edregtime_year = as.numeric(edregtime_year) - 200, edouttime_year = as.numeric(edouttime_year) - 200)
# Take a look
head(admissions)
```

#OpenFDA

### Import OpenFDA
```{r}
# Already installed openfda data
# Load OpenFDA
library(openfda)


library(jsonlite)
fda <- 
  fromJSON("https://api.fda.gov/drug/event.json") %>% 
  janitor::clean_names()

names(fda$results)

```
There are `r length(fda$results)` observations in the `event` dataset under `drug`, they are: `r names(fda$results)`.


