---
title: "length_of_care"
author: "Samantha Brown"
date: "11/17/2018"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(devtools)
library(readr)
library(lubridate)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
admissions <- 
  read.csv("./database/admissions.csv") %>% 
  janitor::clean_names()
names(admissions)
```


```{r}
## Top 10 causes of recorded mortalities
top_causes_of_deaths = admissions %>% 
  filter(deathtime != "NA") %>%
  count(diagnosis) %>% 
  top_n(10)

sepsis = admissions %>% 
  filter(diagnosis == "SEPSIS") %>% 
  mutate(mortality = ifelse(deathtime == "NA", 0, 1))

## Look at top 10 causes of mortalities
mortalities = admissions %>% 
  filter(diagnosis == c("ABDOMINAL PAIN", "ALTERED MENTAL STATUS", "CARDIAC ARREST", "CONGESTIVE HEART FAILURE", "HEAD BLEED", "HYPOTENSION", "INTACRANIAL HEMORRHAGE", "PNEUMONIA", "SEPSIS", "STROKE;TELEMETRY;TRANSIENT ISCHEMIC ATTACK"))
```


## Exploratory:
I want to discuss with you guys the challenge in finding length of care -- if someone was admitted on December 1, 1980 and discharged January 5, 1981, I'm not sure if we can just subtract the times? Using Francis's method, it results in negative number for month. Also, we cannot measure minutes/hours, because admit time does not have minutes

```{r}
## Try to manipulate times in POSIXct format
## Admit time does not have minutes. Only day, month, year

class(admissions$admittime)
class(admissions$dischtime)

time_in = as.POSIXct.Date(admissions$admittime)
time_out = as.POSIXct.Date(admissions$dischtime)
```

```{r}
## Manipulate time with Francis's method 
admissions <- 
  admissions %>% 
  separate(admittime, into = c("admittime_year", "admittime_month", "admittime_day"), sep = "-")
admissions <- 
  admissions %>% 
  separate(dischtime, into = c("dischtime_year", "dischtime_month", "dischtime_day"), sep = "-") %>% 
  separate(dischtime_day, into = c("dischtime_day", "dischtime_time"), sep = " ")
admissions <- 
  admissions %>% 
  separate(deathtime, into = c("deathtime_year", "deathtime_month", "deathtime_day"), sep = "-") %>% 
  separate(deathtime_day, into = c("deathtime_day", "deathtime_time"), sep = " ")
admissions <- 
  admissions %>% 
  separate(edregtime, into = c("edregtime_year", "edregtime_month", "edregtime_day"), sep = "-") %>% 
  separate(edregtime_day, into = c("edregtime_day", "edregtime_time"), sep = " ")
admissions <- 
  admissions %>% 
  separate(edouttime, into = c("edouttime_year", "edouttime_month", "edouttime_day"), sep = "-") %>% 
  separate(edouttime_day, into = c("edouttime_day", "edouttime_time"), sep = " ")

# Correct year to normal
admissions <- 
  admissions %>% 
  mutate(admittime_year = as.numeric(admittime_year) - 200, dischtime_year = as.numeric(dischtime_year) - 200, deathtime_year = as.numeric(deathtime_year) - 200, edregtime_year = as.numeric(edregtime_year) - 200, edouttime_year = as.numeric(edouttime_year) - 200)
```



```{r}
## Laura's Method
admissions_data <- read_csv("./database/data/admissions.csv") %>% 
  janitor::clean_names()
admissions_data %>% 
  mutate(difference = dischtime - admittime) %>% 
  select(difference)

```

