---
title: "Proposal"
author: "Laura Cosgrove"
date: "11/6/2018"
output: github_document
---

```{r setup}
```

## Proposal

* The group members (names and UNIs)
The members of this group are Samantha Brown (UNI: slb2240), Laura Cosgrove (UNI: lec2197), and Francis Z. Fang (UNI: zf2211). Our final project, **Title Name**, will consider three datasets: MIMIC-Physio net, a critical care database used in many open research prokects; AHRQ Medical Expenditure Panel Survey, specifically the CPT part; and OpenFDA. 


* The tentative project title

* The motivation for this project

* The intended final products

* The anticipated data sources

MIMIC-physio net is a critical care database used in many open research projects. 

AHRQ MEPS data CPT part

* The planned analyses / visualizations / coding challenges

* The planned timeline

Our planned timeline is as follows:

*  Sunday, November 11: wrangling meeting (clean and tidy data; divie up analyses)
*  Thursday, November 15: meet to discuss individual initial analyses
*  Thursday, November 15 - Thursday November 29: continue/finish analyses
*  Thursday, November 29: combine our analyses to make a synthesized report
*  Sunday, December 2: make webpage and screencast
*  Thursday, December 6: report, webpage, screencast, peer assessments due
*  Tuesday, December 11: in-class discussion of projects
