---
title: "Severity Scores and Predicting Mortality"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, echo = FALSE, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
library(modelr)

predictor_detail_data <- read_csv("./database/predictor_detail_data.csv")
admissions <- read_csv("./database/data/ADMISSIONS.csv.gz") %>% 
  janitor::clean_names()
subject_diag_cat <- read_csv("./database/subject_diag_cat.csv")

#Deadliest diagnosis
deadly_diagnoses <- subject_diag_cat %>% group_by(category) %>% add_tally %>% mutate(deadly = sum(death_bin)/n) %>% distinct(category, .keep_all = TRUE) %>% select(category, n, deadly) %>% arrange(desc(deadly)) %>% ungroup() %>%  top_n(50)

common_diagnoses <- subject_diag_cat %>% group_by(category) %>% add_tally %>% select(category, n) %>% arrange(desc(n)) %>% distinct(category, .keep_all = TRUE) %>% ungroup() %>%  top_n(50)


predictor_detail_data <- predictor_detail_data %>% 
  distinct(icustay_id, .keep_all = TRUE) %>% 
#Need a couple more variables
  inner_join(admissions, by = "hadm_id") %>% 
  inner_join(subject_diag_cat,  by = "hadm_id")  %>% 
  select(icustay_id, death_bin.x, admission_type.x, admission_age, admission_location, insurance, religion, language, marital_status, gender, ethnicity.x, admit_diagnosis, has_chartevents_data, short_title, category, sapsii:oasis, los_hospital, los_icu) %>% 
  rename(death_bin = death_bin.x, admission_type = admission_type.x, ethnicity = ethnicity.x, diagnosis = category) %>% 
  mutate(admission_type = factor(admission_type), admission_age = as.integer(admission_age), insurance = factor(insurance), religion = factor(religion), marital_status = factor(marital_status), ethnicity = factor(ethnicity), diagnosis = factor(diagnosis)) 

predictor_detail_data_tidy <- predictor_detail_data %>% 
  distinct(icustay_id, .keep_all = TRUE) %>% 
  gather(key = score, value = score_value, sapsii, sofa, lods, apsiii, oasis) %>% 
  select(icustay_id, score, score_value, everything()) 
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r, echo = FALSE, message = FALSE}

insurances <- predictor_detail_data_tidy %>% distinct(insurance)
# selectInput widget
selectInput("insurance", label = h3("Select insurance"),
            choices = insurances, selected = "Medicare")

max_age = predictor_detail_data_tidy %>% distinct(admission_age) %>% filter(admission_age %in% 5:100) %>%  max()
min_age = predictor_detail_data_tidy %>% distinct(admission_age) %>% filter(admission_age %in% 1:100) %>%  min()
  
# sliderInput widget
sliderInput("admission_age", label = h3("Choose age at admission"), min = min_age, 
            max = max_age, value = c(60, 89))

diagnoses <- common_diagnoses %>% distinct(category)

# selectInput widget
selectInput("diagnosis", label = h3("Select diagnosis category"),
            choices = diagnoses, selected = "Septicemia (except in labor)")

renderPrint({
  score_data_tidy <- predictor_detail_data_tidy %>% 
  filter(insurance == input$insurance,
         admission_age %in% input$admission_age[1]:input$admission_age[2],
         diagnosis == input$diagnosis)  %>% 
  select(score, death_bin, score_value, everything()) %>% 
  group_by(score) %>% 
  nest() %>% 
  mutate(glm = map(data, ~glm(death_bin ~ score_value, family = binomial, data = .))) %>% 
  mutate(glm_coef = map(glm, broom::tidy)) %>% 
  mutate(predictions = map2(data, glm, modelr::add_predictions)) %>% 
  select(score, predictions) %>% 
  unnest() %>% 
  mutate(prob_death = exp(pred)/(1 + exp(pred))) %>% 
  mutate(prob_death = if_else(score == "sapsii", 
                              exp(-7.7631 + 0.07237*score_value + 0.9971*log(1 + score_value))/(1 + exp(-7.7631 +  0.07237*score_value + 0.9971*log(1 + score_value))), 
                              prob_death))

})
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, , echo = FALSE, message = FALSE}
renderPlotly({
score_data_tidy <- predictor_detail_data_tidy %>% 
  filter(insurance == input$insurance,
         admission_age %in% input$admission_age[1]:input$admission_age[2],
         diagnosis == input$diagnosis)  %>% 
  select(score, death_bin, score_value, everything()) %>% 
  group_by(score) %>% 
  nest() %>% 
  mutate(glm = map(data, ~glm(death_bin ~ score_value, family = binomial, data = .))) %>% 
  mutate(glm_coef = map(glm, broom::tidy)) %>% 
  mutate(predictions = map2(data, glm, modelr::add_predictions)) %>% 
  select(score, predictions) %>% 
  unnest() %>% 
  mutate(prob_death = exp(pred)/(1 + exp(pred))) %>% 
  mutate(prob_death = if_else(score == "sapsii", 
                              exp(-7.7631 + 0.07237*score_value + 0.9971*log(1 + score_value))/(1 + exp(-7.7631 +  0.07237*score_value + 0.9971*log(1 + score_value))), 
                              prob_death))

for_roc <- score_data_tidy %>% 
  select(score, death_bin, prob_death) %>% 
  group_by(score) %>% 
  nest()

###############ROC AUC Functions#############################
#This code could be improved with a better function.

roc_log_fcn <- function(result, y_prob){
  probs <- seq(0,1, by = 0.005)
  roc_log <- matrix(0, nrow = length(probs), ncol=2)
  i <- 1
  for(p in probs){
    pred <- y_prob > p
    ##False positive rate
    FPR <- sum(!result & pred)/sum(!result)
    ##True positive rate
    TPR <- sum(result & pred)/sum(result)
    roc_log[i,] <- c(FPR, TPR)
    i <- i + 1
  }
  return(roc_log)
}

#SAPSII
sapsii_for_roc <- for_roc %>% 
  filter(score == "sapsii") %>% 
  unnest() 
roc_log_sapsii <- roc_log_fcn(sapsii_for_roc$death_bin, sapsii_for_roc$prob_death)

#SOFA
sofa_for_roc <- for_roc %>% 
  filter(score == "sofa") %>% 
  unnest() 
roc_log_sofa <- roc_log_fcn(sofa_for_roc$death_bin, sofa_for_roc$prob_death)

#LODS
lods_for_roc <- for_roc %>% 
  filter(score == "lods") %>% 
  unnest() 
roc_log_lods <- roc_log_fcn(lods_for_roc$death_bin, lods_for_roc$prob_death)

#APSIII
apsiii_for_roc <- for_roc %>% 
  filter(score == "apsiii") %>% 
  unnest() 
roc_log_apsiii <- roc_log_fcn(apsiii_for_roc$death_bin, apsiii_for_roc$prob_death)

#OASIS
oasis_for_roc <- for_roc %>% 
  filter(score == "oasis") %>% 
  unnest() 
roc_log_oasis <- roc_log_fcn(oasis_for_roc$death_bin, oasis_for_roc$prob_death)


tidy_for_roc <- tibble(FPR_sapsii = roc_log_sapsii[,1], TPR_sapsii = roc_log_sapsii[,2],
       FPR_sofa = roc_log_sofa[,1], TPR_sofa = roc_log_sofa[,2],
       FPR_lods = roc_log_lods[,1], TPR_lods = roc_log_lods[,2],
       FPR_apsiii = roc_log_apsiii[,1], TPR_apsiii = roc_log_apsiii[,2],
       FPR_oasis = roc_log_oasis[,1], TPR_oasis = roc_log_oasis[,2]) %>% 
  gather(key = score, value = FPR, starts_with("FPR")) %>% 
  gather(key = score2, value = TPR, starts_with("TPR")) %>% 
  mutate(score = if_else(score == "FPR_sapsii", 
                         #yes sapsii
                         if_else(score2 == "TPR_sapsii", "sapsii", "NA"),
                         #no sapsii 
                            (if_else(score == "FPR_sofa", 
                              # yes sofa 
                              if_else(score2 == "TPR_sofa", "sofa", "NA"), 
                              # no sofa
                              (if_else(score == "FPR_lods",
                              #yes lods
                                if_else(score2 == "TPR_lods", "lods", "NA"),
                              # no lods
                              (if_else(score == "FPR_apsiii",
                                if_else(score2 == "TPR_apsiii", "apsiii", "NA"), 
                              (if_else(score == "FPR_oasis", 
                                if_else(score2 == "TPR_oasis", "oasis", "NA"), "NA"
                              )))))))))
                         ) %>% 
  filter(score != "NA")


 
plot_roc <- tidy_for_roc %>% 
  select(score, FPR, TPR) %>% 
  ggplot(aes(x = FPR, y = TPR, color = score)) +
  geom_point() +
  geom_step() +
  labs(title = "ROC Curves") +
  theme_bw() +
  scale_color_viridis_d()

ggplotly(plot_roc)
  

})


```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, echo = FALSE, message = FALSE}
renderPlotly({
score_data_tidy <- predictor_detail_data_tidy %>% 
  filter(insurance == input$insurance,
         admission_age %in% input$admission_age[1]:input$admission_age[2],
         diagnosis == input$diagnosis)  %>% 
  select(score, death_bin, score_value, everything()) %>% 
  group_by(score) %>% 
  nest() %>% 
  mutate(glm = map(data, ~glm(death_bin ~ score_value, family = binomial, data = .))) %>% 
  mutate(glm_coef = map(glm, broom::tidy)) %>% 
  mutate(predictions = map2(data, glm, modelr::add_predictions)) %>% 
  select(score, predictions) %>% 
  unnest() %>% 
  mutate(prob_death = exp(pred)/(1 + exp(pred))) %>% 
  mutate(prob_death = if_else(score == "sapsii", 
                              exp(-7.7631 + 0.07237*score_value + 0.9971*log(1 + score_value))/(1 + exp(-7.7631 +  0.07237*score_value + 0.9971*log(1 + score_value))), 
                              prob_death))

plot_prop <- score_data_tidy %>% 
  select(score, death_bin, prob_death) %>% 
  group_by(score, prob_death) %>%
  add_tally(death_bin) %>% 
  rename(tot_death_by_group = n) %>% 
  add_tally() %>% 
  mutate(prop_death = tot_death_by_group/n) %>% 
  ggplot(aes(x = prob_death, y = prop_death, color = score)) + 
  geom_point() +
  geom_abline(slope = 1, intercept = 0) +
  labs(x = "Probability of Death from Mainterm Regression or Literature Value",
       y = "True Proportion of Deaths") 

ggplotly(plot_prop)
})

```

### Total Deaths 2010-2012 {.value-box}

With your selected inputs, the number of deaths observed in the MIMIC database is: 
```{r, echo = FALSE, message = FALSE}

renderValueBox({ 
  value <- paste(predictor_detail_data_tidy %>% filter(insurance == input$insurance, admission_age %in% input$admission_age[1]:input$admission_age[2], diagnosis == input$diagnosis) %>% summarize(sum(death_bin)))
    valueBox(value)

})
```